version: '3'
services:
  app:
    restart: always
    container_name: nestjs_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    links:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE_NAME: test


  database:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - database


volumes:
  pg_data:
